.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. atlacoin_qt test_atlacoin_qt
clean: FORCE
	$(MAKE) -C .. atlacoin_qt_clean test_atlacoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_atlacoin_qt_check
atlacoin-qt atlacoin-qt.exe: FORCE
	 $(MAKE) -C .. atlacoin_qt
